spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_crm
    username: gym_user
    password: gym_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      jakarta:
        persistence:
          validation:
            mode: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
