spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gym_crm}
    username: ${DB_USERNAME:gym_user}
    password: ${DB_PASSWORD:gym_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
