spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    show-sql: true

security:
  jwt:
    secret: ${JWT_SECRET}
  service:
    secret: ${SERVICE_JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
