spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gym_crm}
    username: ${DB_USERNAME:gym_user}
    password: ${DB_PASSWORD:gym_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    show-sql: true

security:
  jwt:
    secret: ${JWT_SECRET:local-only-dev-secret-key-not-for-prod-use-1234567890}
  admin:
    password-hash: "$2a$12$LkD4jAbeW2jSK/tFWYHxX.GDiaijMX/6/RYS87k5W3UfNH5JFhSpu"

management:
  endpoints:
    web:
      exposure:
        include: "*"
