spring:
  application:
    name: gym-crm
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
      jakarta:
        persistence:
          validation:
            mode: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

security:
  jwt:
    expiration-ms: 3600000
  cors:
    allowed-origins:
      - "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
